#!/bin/bash
# Set up a PRIVATE obfs4 bridge for the drift study. Run this ON the bridge
# host, not on the collection machine.
#
# Private means the bridge is never published to the bridge authority and never
# distributed by BridgeDB. Only the collection host connects to it. That is the
# whole point: volunteer bridges churn, and this study needs one obfs4 path that
# stays identical from September to December. Five volunteer bridges died under
# us in a single afternoon before this existed.
#
#   scripts/collection/setup_obfs4_bridge.sh [public_ip] [obfs4_port]

set -euo pipefail

PUBLIC_IP="${1:-$(curl -fsS --max-time 10 https://api.ipify.org)}"
OBFS4_PORT="${2:-9010}"
OR_PORT="${TOR_WF_BRIDGE_ORPORT:-9001}"
NICKNAME="${TOR_WF_BRIDGE_NICKNAME:-wfthesis}"

echo "=== private obfs4 bridge on ${PUBLIC_IP}:${OBFS4_PORT} ==="

if ! command -v tor >/dev/null || ! command -v obfs4proxy >/dev/null; then
	echo "[*] installing tor and obfs4proxy"
	sudo apt-get update -qq
	sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq tor obfs4proxy
fi

OBFS4_BIN="$(command -v obfs4proxy)"

echo "[*] writing /etc/tor/torrc"
sudo tee /etc/tor/torrc >/dev/null <<EOF
# Private obfs4 bridge for the Tor WF concept drift study.
# Generated by setup_obfs4_bridge.sh. Do not hand-edit.

BridgeRelay 1
ORPort ${OR_PORT}
ExtORPort auto
ServerTransportPlugin obfs4 exec ${OBFS4_BIN}
ServerTransportListenAddr obfs4 0.0.0.0:${OBFS4_PORT}
Nickname ${NICKNAME}

# The cloud NAT hides the public address from Tor, so state it explicitly.
Address ${PUBLIC_IP}

# Never published to the bridge authority, never handed out by BridgeDB.
PublishServerDescriptor 0
BridgeDistribution none

# Only the obfs4 port is reachable from outside; the ORPort is used locally by
# obfs4proxy. Without this Tor waits forever on a self-reachability test that
# can never succeed.
AssumeReachable 1

# This is a relay, not a client. No SOCKS port needed.
SocksPort 0

Log notice file /var/log/tor/notices.log
EOF

echo "[*] restarting tor"
sudo systemctl enable tor >/dev/null 2>&1 || true
sudo systemctl restart tor@default
sleep 8

for _ in $(seq 1 20); do
	[ -s /var/lib/tor/fingerprint ] && [ -s /var/lib/tor/pt_state/obfs4_bridgeline.txt ] && break
	sleep 2
done

if ! sudo test -s /var/lib/tor/fingerprint; then
	echo "FAILED: no fingerprint generated. Recent log:"
	sudo tail -20 /var/log/tor/notices.log 2>/dev/null || sudo journalctl -u tor@default -n 20 --no-pager
	exit 1
fi

FINGERPRINT="$(sudo awk '{print $2}' /var/lib/tor/fingerprint)"
CERT="$(sudo grep -o 'cert=[^ ]*' /var/lib/tor/pt_state/obfs4_bridgeline.txt | head -1)"

if [ -z "$CERT" ]; then
	echo "FAILED: obfs4 certificate not generated yet. Recent log:"
	sudo tail -20 /var/log/tor/notices.log
	exit 1
fi

BRIDGE_LINE="Bridge obfs4 ${PUBLIC_IP}:${OBFS4_PORT} ${FINGERPRINT} ${CERT} iat-mode=0"

echo
echo "=== bridge line ==="
echo "$BRIDGE_LINE"
echo
echo "Put that in ~/tor_wf_runtime/obfs4/torrc on the collection host,"
echo "restart that instance, and set TOR_WF_COLLECT_OBFS4=1 in .env.collection."
echo
echo "Reminder: the cloud firewall is separate from the host firewall."
echo "TCP ${OBFS4_PORT} must be allowed inbound in the network security group."
