#!/bin/bash
# Create the Tor instances the study needs, without root.
#
# Tor runs fine as an unprivileged user with its own DataDirectory, so the
# system Tor is left untouched.  One instance per transport is needed because
# every arm has to be captured inside the same round, and one Tor cannot be
# unbridged, obfs4-bridged and Snowflake-bridged at once.
#
#   scripts/collection/setup_tor_instances.sh
#   scripts/collection/setup_tor_instances.sh --status
#   scripts/collection/setup_tor_instances.sh --stop
#
# The Snowflake arm needs lyrebird, which no distribution packages; run
# scripts/collection/fetch_pt_bundle.sh first, or it is skipped.

set -euo pipefail

RUNTIME_DIR="${TOR_WF_RUNTIME_DIR:-$HOME/tor_wf_runtime}"
BASELINE_SOCKS="${TOR_WF_BASELINE_SOCKS_PORT:-9060}"
BASELINE_CONTROL="${TOR_WF_BASELINE_CONTROL_PORT:-9061}"
OBFS4_SOCKS="${TOR_WF_OBFS4_SOCKS_PORT:-9062}"
OBFS4_CONTROL="${TOR_WF_OBFS4_CONTROL_PORT:-9063}"
SNOWFLAKE_SOCKS="${TOR_WF_SNOWFLAKE_SOCKS_PORT:-9064}"
SNOWFLAKE_CONTROL="${TOR_WF_SNOWFLAKE_CONTROL_PORT:-9065}"

ARMS="baseline obfs4 snowflake"

control_port_of() {
	case "$1" in
	baseline) echo "$BASELINE_CONTROL" ;;
	obfs4) echo "$OBFS4_CONTROL" ;;
	snowflake) echo "$SNOWFLAKE_CONTROL" ;;
	esac
}

# The baseline arm uses one fixed guard for the whole study, so that a change
# in measured accuracy is drift rather than a different route through the
# network. The guard is discovered on first run and recorded; it is not
# hardcoded, because relays leave the network.
#
# The spring t0 used guard 27A06581 (th4r, 57.129.38.230). That relay is no
# longer in the consensus, so the new series necessarily runs over a different
# guard. Record that as a covariate rather than pretending the path is identical.
GUARD_RECORD="$RUNTIME_DIR/baseline/pinned_guard.txt"
PINNED_GUARD="${TOR_WF_PINNED_GUARD:-}"
PY_BIN="${TOR_WF_PYTHON:-$(command -v python3 || command -v python)}"

TOR_BIN="$(command -v tor || echo /usr/bin/tor)"
OBFS4_BIN="$(command -v obfs4proxy || echo /usr/bin/obfs4proxy)"

# lyrebird carries the Snowflake client and is not packaged by any distribution,
# so it comes from the Expert Bundle that fetch_pt_bundle.sh unpacks.
PT_DIR="$RUNTIME_DIR/pt"
PT_CONFIG="${TOR_WF_PT_CONFIG:-$PT_DIR/tor/pluggable_transports/pt_config.json}"
SNOWFLAKE_BIN="${TOR_WF_SNOWFLAKE_BIN:-}"
if [ -z "$SNOWFLAKE_BIN" ]; then
	if [ -x "$PT_DIR/tor/pluggable_transports/lyrebird" ]; then
		SNOWFLAKE_BIN="$PT_DIR/tor/pluggable_transports/lyrebird"
	else
		SNOWFLAKE_BIN="$(command -v lyrebird || true)"
	fi
fi

snowflake_bridges() {
	"$PY_BIN" - "$PT_CONFIG" <<'PYSF'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as fh:
    for line in json.load(fh).get("bridges", {}).get("snowflake", []):
        print("Bridge " + line)
PYSF
}

status() {
	for name in $ARMS; do
		port="$(control_port_of "$name")"
		pidfile="$RUNTIME_DIR/$name/tor.pid"
		if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
			echo "  $name: running (pid $(cat "$pidfile")), control port $port"
		else
			echo "  $name: not running"
		fi
	done
}

stop_all() {
	for name in $ARMS; do
		pidfile="$RUNTIME_DIR/$name/tor.pid"
		if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
			kill "$(cat "$pidfile")"
			echo "  stopped $name"
		fi
	done
}

case "${1:-}" in
--status)
	status
	exit 0
	;;
--stop)
	stop_all
	exit 0
	;;
esac

# The bridge line is read from the system torrc rather than stored in the
# repository, so the bridge credentials stay off GitHub.
BRIDGE_LINE="${TOR_WF_BRIDGE_LINE:-$(grep -m1 '^Bridge ' /etc/tor/torrc 2>/dev/null || true)}"
if [ -z "$BRIDGE_LINE" ]; then
	echo "WARNING: no Bridge line found in /etc/tor/torrc."
	echo "         The obfs4 arm will not be set up. Set TOR_WF_BRIDGE_LINE to override."
fi

write_instance() {
	local name="$1" socks="$2" control="$3" extra="$4"
	local dir="$RUNTIME_DIR/$name"
	mkdir -p "$dir/data"
	chmod 700 "$dir/data"
	cat >"$dir/torrc" <<EOF
# Generated by setup_tor_instances.sh. Edit the script, not this file.
SocksPort $socks
ControlPort $control
CookieAuthentication 1
DataDirectory $dir/data
PidFile $dir/tor.pid
Log notice file $dir/tor.log
RunAsDaemon 1
$extra
EOF
	echo "  wrote $dir/torrc"
}

echo "=== creating Tor instances under $RUNTIME_DIR ==="

baseline_torrc() {
	local pin="$1"
	if [ -n "$pin" ]; then
		write_instance baseline "$BASELINE_SOCKS" "$BASELINE_CONTROL" "# Guard pinned for the whole study. Recorded in pinned_guard.txt.
EntryNodes $pin
StrictNodes 1
GuardLifetime 180 days"
	else
		write_instance baseline "$BASELINE_SOCKS" "$BASELINE_CONTROL" "GuardLifetime 180 days"
	fi
}

# Reuse a guard pinned by an earlier run, but only if it is still in the
# current consensus. A pin to a departed relay makes Tor unable to build any
# circuit at all, which is how the spring guard failed.
if [ -z "$PINNED_GUARD" ] && [ -f "$GUARD_RECORD" ]; then
	PINNED_GUARD="$(cut -d" " -f1 "$GUARD_RECORD")"
	echo "  reusing recorded guard $PINNED_GUARD"
fi

baseline_torrc "$PINNED_GUARD"

if [ -n "$BRIDGE_LINE" ]; then
	write_instance obfs4 "$OBFS4_SOCKS" "$OBFS4_CONTROL" "UseBridges 1
ClientTransportPlugin obfs4 exec $OBFS4_BIN
$BRIDGE_LINE"
fi

# Snowflake reaches the Tor network through short-lived volunteer WebRTC proxies
# brokered on demand, so there is no bridge of our own to run and no address to
# pin. The bridge lines are Tor Browser's own, taken from the bundle rather than
# copied into this repository, so they stay in step with what real clients use.
if [ -n "$SNOWFLAKE_BIN" ] && [ -f "$PT_CONFIG" ]; then
	SNOWFLAKE_BRIDGES="$(snowflake_bridges)"
fi
if [ -n "${SNOWFLAKE_BRIDGES:-}" ]; then
	write_instance snowflake "$SNOWFLAKE_SOCKS" "$SNOWFLAKE_CONTROL" "UseBridges 1
ClientTransportPlugin snowflake exec $SNOWFLAKE_BIN
$SNOWFLAKE_BRIDGES"
else
	echo "  skipping snowflake: no lyrebird or no bridge lines"
	echo "    (run scripts/collection/fetch_pt_bundle.sh to provide both)"
fi

start_instance() {
	local name="$1"
	local dir="$RUNTIME_DIR/$name"
	local pidfile="$dir/tor.pid"
	if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
		echo "  $name already running (pid $(cat "$pidfile"))"
		return 0
	fi
	: >"$dir/tor.log"
	"$TOR_BIN" -f "$dir/torrc" >"$dir/start.log" 2>&1 || {
		echo "  FAILED to start $name, see $dir/start.log"
		tail -5 "$dir/start.log"
		return 1
	}
	return 0
}

stop_instance() {
	local pidfile="$RUNTIME_DIR/$1/tor.pid"
	if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
		kill "$(cat "$pidfile")"
		sleep 3
	fi
}

wait_bootstrap() {
	local name="$1" limit="${2:-90}"
	local dir="$RUNTIME_DIR/$name"
	for _ in $(seq 1 "$limit"); do
		if grep -q "Bootstrapped 100%" "$dir/tor.log" 2>/dev/null; then
			echo "  $name: bootstrapped"
			return 0
		fi
		sleep 2
	done
	echo "  $name: NOT bootstrapped, last status:"
	grep -oE "Bootstrapped [0-9]+%.*" "$dir/tor.log" 2>/dev/null | tail -1 | sed "s/^/      /"
	return 1
}

# Ask a bootstrapped instance which relay it is actually using as its guard.
discover_guard() {
	"$PY_BIN" - "$BASELINE_CONTROL" <<'PYGUARD'
import sys
from stem.control import Controller
port = int(sys.argv[1])
with Controller.from_port(port=port) as c:
    c.authenticate()
    circuits = [x for x in c.get_circuits() if x.status == "BUILT" and x.path]
    if not circuits:
        c.new_circuit(await_build=True, timeout=90)
        circuits = [x for x in c.get_circuits() if x.status == "BUILT" and x.path]
    fp = circuits[0].path[0][0]
    ns = c.get_network_status(fp, default=None)
    print(fp, ns.nickname if ns else "?", ns.address if ns else "?")
PYGUARD
}

# Verify a candidate pin is in the consensus the instance can actually see.
guard_in_consensus() {
	"$PY_BIN" - "$BASELINE_CONTROL" "$1" <<'PYCHECK'
import sys
from stem.control import Controller
port, fp = int(sys.argv[1]), sys.argv[2].upper()
with Controller.from_port(port=port) as c:
    c.authenticate()
    print("yes" if any(d.fingerprint == fp for d in c.get_network_statuses()) else "no")
PYCHECK
}

BASELINE_DIR="$RUNTIME_DIR/baseline"

# A fresh Tor pinned to a single guard cannot bootstrap: it needs
# microdescriptors before it can use the guard, and a circuit through the guard
# to fetch them. So bootstrap unrestricted first, then apply the pin.
if [ -z "$PINNED_GUARD" ] || ! ls "$BASELINE_DIR"/data/cached-microdesc* >/dev/null 2>&1; then
	echo "=== baseline: unrestricted bootstrap to prime the directory cache ==="
	baseline_torrc ""
	start_instance baseline && wait_bootstrap baseline 90

	if [ -z "$PINNED_GUARD" ]; then
		echo "  discovering which guard Tor selected..."
		if GUARD_INFO="$(discover_guard 2>/dev/null)" && [ -n "$GUARD_INFO" ]; then
			PINNED_GUARD="$(echo "$GUARD_INFO" | cut -d" " -f1)"
			echo "$GUARD_INFO" >"$GUARD_RECORD"
			echo "  selected guard: $GUARD_INFO"
		else
			echo "  WARNING: could not determine the guard; continuing unpinned."
		fi
	fi
	stop_instance baseline
fi

if [ -n "$PINNED_GUARD" ]; then
	if [ "$(guard_in_consensus "$PINNED_GUARD" 2>/dev/null || echo no)" = "no" ]; then
		echo "  WARNING: guard $PINNED_GUARD is not in the current consensus."
		echo "           Discarding the pin so Tor can still build circuits."
		rm -f "$GUARD_RECORD"
		PINNED_GUARD=""
	fi
fi
baseline_torrc "$PINNED_GUARD"

echo "=== starting instances ==="
for name in $ARMS; do
	[ -f "$RUNTIME_DIR/$name/torrc" ] || continue
	start_instance "$name"
done

echo "=== waiting for bootstrap ==="
for name in $ARMS; do
	[ -f "$RUNTIME_DIR/$name/torrc" ] || continue
	wait_bootstrap "$name" 90 || true
done

echo
status
echo
if [ -f "$GUARD_RECORD" ]; then
	echo "Baseline guard pinned for the study: $(cat "$GUARD_RECORD")"
	echo "  (spring t0 used th4r/27A06581, which has since left the consensus)"
fi
echo
echo "Add these to .env.collection:"
echo "  TOR_WF_BASELINE_SOCKS_PORT=$BASELINE_SOCKS"
echo "  TOR_WF_BASELINE_CONTROL_PORT=$BASELINE_CONTROL"
echo "  TOR_WF_OBFS4_SOCKS_PORT=$OBFS4_SOCKS"
echo "  TOR_WF_OBFS4_CONTROL_PORT=$OBFS4_CONTROL"
if [ -f "$RUNTIME_DIR/snowflake/torrc" ]; then
	echo "  TOR_WF_SNOWFLAKE_SOCKS_PORT=$SNOWFLAKE_SOCKS"
	echo "  TOR_WF_SNOWFLAKE_CONTROL_PORT=$SNOWFLAKE_CONTROL"
	echo "  TOR_WF_COLLECT_SNOWFLAKE=1   # off by default"
fi
