#!/bin/bash
# Create the two Tor instances the drift study needs, without root.
#
# Tor runs fine as an unprivileged user with its own DataDirectory, so the
# system Tor is left untouched.  Two instances are needed because the baseline
# and obfs4 arms have to be captured inside the same round, and one Tor cannot
# be both bridged and unbridged at once.
#
#   scripts/collection/setup_tor_instances.sh
#   scripts/collection/setup_tor_instances.sh --status
#   scripts/collection/setup_tor_instances.sh --stop

set -euo pipefail

RUNTIME_DIR="${TOR_WF_RUNTIME_DIR:-$HOME/tor_wf_runtime}"
BASELINE_SOCKS="${TOR_WF_BASELINE_SOCKS_PORT:-9060}"
BASELINE_CONTROL="${TOR_WF_BASELINE_CONTROL_PORT:-9061}"
OBFS4_SOCKS="${TOR_WF_OBFS4_SOCKS_PORT:-9062}"
OBFS4_CONTROL="${TOR_WF_OBFS4_CONTROL_PORT:-9063}"

# The guard used for every baseline capture in the spring 2026 t0 collection.
# Pinning it means the new series shares t0's network path, so a change in
# measured accuracy is drift and not a different route through the network.
PINNED_GUARD="${TOR_WF_PINNED_GUARD:-27A06581F1CE22D1BA4D160F6E7C7AABAC176242}"

TOR_BIN="$(command -v tor || echo /usr/bin/tor)"
OBFS4_BIN="$(command -v obfs4proxy || echo /usr/bin/obfs4proxy)"

status() {
	for pair in "baseline:$BASELINE_CONTROL" "obfs4:$OBFS4_CONTROL"; do
		name="${pair%%:*}"
		port="${pair##*:}"
		pidfile="$RUNTIME_DIR/$name/tor.pid"
		if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
			echo "  $name: running (pid $(cat "$pidfile")), control port $port"
		else
			echo "  $name: not running"
		fi
	done
}

stop_all() {
	for name in baseline obfs4; do
		pidfile="$RUNTIME_DIR/$name/tor.pid"
		if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
			kill "$(cat "$pidfile")"
			echo "  stopped $name"
		fi
	done
}

case "${1:-}" in
--status)
	status
	exit 0
	;;
--stop)
	stop_all
	exit 0
	;;
esac

# The bridge line is read from the system torrc rather than stored in the
# repository, so the bridge credentials stay off GitHub.
BRIDGE_LINE="${TOR_WF_BRIDGE_LINE:-$(grep -m1 '^Bridge ' /etc/tor/torrc 2>/dev/null || true)}"
if [ -z "$BRIDGE_LINE" ]; then
	echo "WARNING: no Bridge line found in /etc/tor/torrc."
	echo "         The obfs4 arm will not be set up. Set TOR_WF_BRIDGE_LINE to override."
fi

write_instance() {
	local name="$1" socks="$2" control="$3" extra="$4"
	local dir="$RUNTIME_DIR/$name"
	mkdir -p "$dir/data"
	chmod 700 "$dir/data"
	cat >"$dir/torrc" <<EOF
# Generated by setup_tor_instances.sh. Edit the script, not this file.
SocksPort $socks
ControlPort $control
CookieAuthentication 1
DataDirectory $dir/data
PidFile $dir/tor.pid
Log notice file $dir/tor.log
RunAsDaemon 1
$extra
EOF
	echo "  wrote $dir/torrc"
}

echo "=== creating Tor instances under $RUNTIME_DIR ==="

write_instance baseline "$BASELINE_SOCKS" "$BASELINE_CONTROL" "# Pin the same guard the spring t0 used.
# If this relay leaves the network the instance stops working entirely, which
# preflight will report. That is preferable to silently changing the path.
EntryNodes $PINNED_GUARD
StrictNodes 1
GuardLifetime 180 days"

if [ -n "$BRIDGE_LINE" ]; then
	write_instance obfs4 "$OBFS4_SOCKS" "$OBFS4_CONTROL" "UseBridges 1
ClientTransportPlugin obfs4 exec $OBFS4_BIN
$BRIDGE_LINE"
fi

for name in baseline obfs4; do
	dir="$RUNTIME_DIR/$name"
	[ -f "$dir/torrc" ] || continue
	pidfile="$dir/tor.pid"
	if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile")" 2>/dev/null; then
		echo "  $name already running (pid $(cat "$pidfile"))"
		continue
	fi
	echo "  starting $name..."
	"$TOR_BIN" -f "$dir/torrc" >"$dir/start.log" 2>&1 || {
		echo "  FAILED to start $name, see $dir/start.log"
		tail -5 "$dir/start.log"
		continue
	}
done

echo "=== waiting for bootstrap (up to 120s) ==="
for name in baseline obfs4; do
	dir="$RUNTIME_DIR/$name"
	[ -f "$dir/torrc" ] || continue
	for _ in $(seq 1 60); do
		if grep -q "Bootstrapped 100%" "$dir/tor.log" 2>/dev/null; then
			echo "  $name: bootstrapped"
			break
		fi
		sleep 2
	done
	grep -q "Bootstrapped 100%" "$dir/tor.log" 2>/dev/null ||
		echo "  $name: NOT bootstrapped yet, check $dir/tor.log"
done

echo
status
echo
echo "Add these to .env.collection:"
echo "  TOR_WF_BASELINE_SOCKS_PORT=$BASELINE_SOCKS"
echo "  TOR_WF_BASELINE_CONTROL_PORT=$BASELINE_CONTROL"
echo "  TOR_WF_OBFS4_SOCKS_PORT=$OBFS4_SOCKS"
echo "  TOR_WF_OBFS4_CONTROL_PORT=$OBFS4_CONTROL"
