"""Site lists for the thesis collection: monitored, unmonitored and background.

The monitored set keeps the 36 spring sites, so the spring traces stay a usable
reference, minus Amazon, which served a bot challenge on every arm in the
Snowflake pilot and so would only ever contribute rejected captures. Fifteen
sites are added to reach the 50 the thesis plan names.

The unmonitored and background pools are generated by build_site_lists.py from
a pinned Tranco list and written to sites/*.txt, so the exact open-world set is
part of the repository and not whatever the ranking says on the day someone
reruns it.
"""

import os
from urllib.parse import urlparse

SITES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sites")

MONITORED = {
    # The spring 2026 list, without amazon.
    "wikipedia": "https://en.wikipedia.org/wiki/Main_Page",
    "duckduckgo": "https://duckduckgo.com",
    "github": "https://github.com",
    "stackoverflow": "https://stackoverflow.com",
    "mit_ocw": "https://ocw.mit.edu",
    "gnu": "https://www.gnu.org",
    "debian": "https://www.debian.org",
    "w3c": "https://www.w3.org",
    "bbc": "https://www.bbc.com",
    "cnn": "https://www.cnn.com",
    "reuters": "https://www.reuters.com",
    "theguardian": "https://www.theguardian.com/international",
    "aljazeera": "https://www.aljazeera.com",
    "hacker_news": "https://news.ycombinator.com",
    "wired": "https://www.wired.com",
    "techcrunch": "https://techcrunch.com",
    "telex": "https://telex.hu",
    "index": "https://index.hu",
    "hvg": "https://hvg.hu",
    "origo": "https://www.origo.hu",
    "hwsw": "https://www.hwsw.hu",
    "bme": "https://www.bme.hu",
    "ebay": "https://www.ebay.com",
    "aliexpress": "https://www.aliexpress.com",
    "imdb": "https://www.imdb.com",
    "reddit": "https://old.reddit.com",
    "twitch": "https://www.twitch.tv",
    "vimeo": "https://vimeo.com",
    "soundcloud": "https://soundcloud.com",
    "wordpress": "https://wordpress.org",
    "mozilla": "https://www.mozilla.org",
    "archive": "https://archive.org",
    "medium": "https://medium.com",
    "quora": "https://www.quora.com",
    "coursera": "https://www.coursera.org",
    # Added for the thesis: more news, more Hungarian, and the privacy sites
    # a Tor user is plausibly monitored for visiting.
    "python": "https://www.python.org",
    "kernel": "https://www.kernel.org",
    "archlinux": "https://archlinux.org",
    "torproject": "https://www.torproject.org",
    "eff": "https://www.eff.org",
    "signal": "https://signal.org",
    "npr": "https://www.npr.org",
    "apnews": "https://apnews.com",
    "dw": "https://www.dw.com/en",
    "spiegel": "https://www.spiegel.de",
    "arstechnica": "https://arstechnica.com",
    "theverge": "https://www.theverge.com",
    "444": "https://444.hu",
    "24hu": "https://24.hu",
    "portfolio": "https://www.portfolio.hu",
}


def registrable(host):
    """Last two labels of a hostname; good enough to keep pools disjoint."""
    host = (host or "").lower().strip(".")
    if host.startswith("www."):
        host = host[4:]
    return ".".join(host.split(".")[-2:])


def monitored_domains():
    return {registrable(urlparse(u).hostname) for u in MONITORED.values()}


def load_pool(name):
    """Read sites/<name>.txt: one 'label url' per line, '#' comments allowed."""
    path = os.path.join(SITES_DIR, f"{name}.txt")
    pool = {}
    if not os.path.exists(path):
        return pool
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            label, url = line.split()
            pool[label] = url
    return pool
